function = "bin.tabpack.tabpack.main"
n_seeds = 5

[base_config]
n_models = 5
batch_size = 256
n_epochs = -1
patience = 16
amp_dtype = "bfloat16"
save_all_predictions = true
track_online_ensemble_history = true
track_experiments = true

[base_config.data]
path = "data/churn"
num_policy = "noisy-quantile"
extract_bin_from_num = true
bin_policy = "convert-to-cat"
cat_policy = "ordinal"
cache = true

[base_config.model]
activation = "ReLU"
d_block = 384

[base_config.model.num_embeddings]
type = "CosineEmbeddingsPack"

[base_config.optimizer]
type = "MuonAdamWPack"
shared_step = true

[base_config.online_ensembles.greedy]
type = "greedy"
update_type = "latest"
include_current_ensemble_in_pool = true
patience = 32

[base_config.online_ensembles.greedy.options]
max_ensemble_size = 32

[[base_config.configs]]

[base_config.configs.model]
n_blocks = 2
dropout = 0.3650610147583848

[base_config.configs.model.num_embeddings]
d_embedding = 16
init_scale = 0.15655364608361647

[base_config.configs.optimizer]
lr = 0.00022725750538844292
weight_decay = 0.0036189202913092865
muon_lr = 0.07740068067629041

[[base_config.configs]]

[base_config.configs.model]
n_blocks = 3
dropout = 0.0

[base_config.configs.model.num_embeddings]
d_embedding = 32
init_scale = 0.04955698533896726

[base_config.configs.optimizer]
lr = 0.004100758595064546
weight_decay = 0.6670111812059988
muon_lr = 0.03966479140571722

[[base_config.configs]]

[base_config.configs.model]
n_blocks = 1
dropout = 0.4782028613979744

[base_config.configs.model.num_embeddings]
d_embedding = 12
init_scale = 5.151715421583566

[base_config.configs.optimizer]
lr = 0.000839286035918741
weight_decay = 0.023481955729256928
muon_lr = 0.05808751805281262

[[base_config.configs]]

[base_config.configs.model]
n_blocks = 2
dropout = 0.12934203344470385

[base_config.configs.model.num_embeddings]
d_embedding = 28
init_scale = 0.012586757923192084

[base_config.configs.optimizer]
lr = 0.004258757183456561
weight_decay = 0.011644116593520673
muon_lr = 0.005169086274454182

[[base_config.configs]]

[base_config.configs.model]
n_blocks = 2
dropout = 0.11887091300781938

[base_config.configs.model.num_embeddings]
d_embedding = 20
init_scale = 6.725906088135357

[base_config.configs.optimizer]
lr = 0.0011943815093126947
weight_decay = 0.3998234077447628
muon_lr = 0.07593104531793193
