from typing import Literal, NamedTuple, Optional, Sequence  # noqa: UP035

import vh3

# NOTE
# The code for `python_3_deep_learning` and `clone_a_repo_ext` is mostly generated by:
# `uv run --group yandex --no-dev python -m vh3 import <operation link>`
#
# Modifications:
# - Some arguments are added to `python_3_deep_learning`.
# - The code is formatted.


class Python3DeepLearningOutputs(NamedTuple):
    data: vh3.Binary
    state: vh3.Binary
    logs: vh3.Binary
    json_output: vh3.JSON
    pulsar_link: vh3.HTML
    pulsar_info: vh3.JSON


@vh3.decorator.external_operation(
    'https://nirvana.yandex-team.ru/operation/ccfea9be-fe69-4129-8ce8-df320bd33475/overview'
)
@vh3.decorator.nirvana_names_transformer(
    vh3.name_transformers.snake_to_dash, options=True
)
def python_3_deep_learning(
    *,
    pulsar_token: vh3.Secret,
    script: Optional[vh3.Binary] = None,  # noqa: UP045
    data: Sequence[vh3.Binary] = (),
    state: Optional[vh3.Binary] = None,  # noqa: UP045
    params: Optional[vh3.JSON] = None,  # noqa: UP045
    pulsar_params: Optional[vh3.JSON] = None,  # noqa: UP045
    image: vh3.MultipleEnums[
        Literal[
            'pydl/nvidia-pytorch:24.10.0',
            'pydl/nvidia-tensorflow:24.10.0',
            'pydl/python:3.11.10.0',
        ]
    ] = ('pydl/python:3.11.10.0',),
    pool_tree: vh3.MultipleEnums[
        Literal[
            'gpu_hutang_141g',
            'gpu_hainan_80g',
            'gpu_a800_80g',
            'gpu_anshan_80g',
            'gpu_tesla_a100_80g',
            'gpu_tesla_a100',
            'gpu_tesla_v100',
            'physical',
        ]
    ] = ('physical',),
    nodes_count: vh3.Integer = 1,
    gpu_count: vh3.Integer = 0,
    pip: vh3.MultipleStrings = (),
    run_command: vh3.String = 'python -c "print(\'Hello, World!\')"',
    openmpi_runner: vh3.Boolean = False,
    openmpi_params: Optional[vh3.String] = None,  # noqa: UP045
    mpi_processes_count: vh3.Integer = -1,
    pulsar: vh3.Boolean = False,
    job_variables: vh3.MultipleStrings = (),
    ttl: vh3.Integer = 1440,
    timestamp: vh3.Date = '2017-08-25T16:40:26+0300',  # type: ignore
    environment: vh3.MultipleStrings = (),
    # >>> Manually added arguments.
    cpu_cores_usage: vh3.Integer,
    max_ram: Optional[vh3.Integer] = None,  # noqa: UP045
    gpu_max_ram: Optional[vh3.Integer] = None,  # noqa: UP045
    max_disk: Optional[vh3.Integer] = None,  # noqa: UP045
    job_scheduler_instance: vh3.String,
    job_scheduler_yt_pool: vh3.String,
    # <<<
) -> Python3DeepLearningOutputs:
    raise NotImplementedError()


@vh3.decorator.external_operation(
    # 'https://nirvana.yandex-team.ru/operation/1fa797f1-7ac4-4355-86b2-cf07b053a9bc/overview',  # hermes  # noqa: E501
    # 'https://nirvana.yandex-team.ru/operation/0809c92e-6052-4733-9be6-fb24f6d1429a/overview',  # inari  # noqa: E501
    'https://nirvana.yandex-team.ru/operation/4416b2f6-92b1-478e-ac0e-1600d8692c78/overview',  # hermes2  # noqa: E501
    vh3.job_run_base,
)
@vh3.decorator.nirvana_names(
    max_ram='max-ram', cpu_guarantee='cpu-guarantee', max_disk='max-disk'
)
@vh3.decorator.nirvana_output_names('repo_archive')
def clone_a_repo_ext(
    *,
    repo: vh3.String,
    folder_name: vh3.String,
    max_ram: vh3.Integer = 1024,
    key: vh3.Secret = '',
    cpu_guarantee: vh3.Integer = 400,
    commit_or_branch: vh3.String = '',
    max_disk: vh3.Integer = 20480,
    submodule_update: vh3.Boolean = False,
    delete_git: vh3.Boolean = False,
    pigz_compression: vh3.Integer = 6,
) -> vh3.Binary:
    raise NotImplementedError()
