#!/usr/bin/env python3
"""
Convert pre-filtered TSV dumps → tabpack dataset format (Polars edition).

Input files (--train / --val / --test, at least one required) are TSV with
pre-filtered columns (generated by YQL query from generate_yql_query.py):
    key \t label \t f_1 \t f_2 \t ... \t f_K

All features are numeric (Float32). No header.

Output (--out-dir):
    x_num.npy                  float32 (N, n_features)
    y.npy                      int64 (binclass/multiclass) | float32 (regression)
    key.npy                    int64  (N,)  — polars hash of the group key
    info.json                  {"task": {"type": ..., "score": ...}}
    splits/default/train.npy   int32  (contiguous ranges, original row order
    splits/default/val.npy      is preserved → groups stay contiguous,
    splits/default/test.npy     ready for future pairlogit/group tasks)

Usage:
    python convert_polars.py --train train.tsv --val val.tsv --test test.tsv \
        --out-dir data/peru --task-type binclass --n-workers 8
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

import numpy as np
import polars as pl
from tqdm import tqdm

BATCH_SIZE = 500_000  # rows per batch for constant memory usage

TASK_SCORES = {
    "binclass": "accuracy",
    "multiclass": "accuracy",
    "regression": "rmse",
    "pairwise": "pair_accuracy",
}

NA_STRINGS = {"", "nan", "null", "none", "\\n", "NaN", "NULL"}


# ── CLI ──────────────────────────────────────────────────────────────────────
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Convert pre-filtered TSV dumps → tabpack format (Polars edition)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--train", type=Path, help="Train split TSV")
    p.add_argument("--val", type=Path, help="Validation split TSV")
    p.add_argument("--test", type=Path, help="Test split TSV")
    p.add_argument("--out-dir", type=Path, required=True, help="Output dataset dir")
    p.add_argument("--task-type", choices=sorted(TASK_SCORES), default="pairwise")
    p.add_argument("--n-workers", type=int, default=os.cpu_count(),
                   help="Number of workers for polars (default: all CPUs)")
    args = p.parse_args()
    if not (args.train or args.val or args.test):
        p.error("at least one of --train / --val / --test is required")
    return args


# ── helpers ──────────────────────────────────────────────────────────────────
def sniff(path: Path) -> int:
    """Return n_features from the first line."""
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            # Format: key \t label \t f_1 \t ... \t f_K
            return len(line.split("\t")) - 2
    raise ValueError(f"{path}: empty file")


# ── loader ───────────────────────────────────────────────────────────────────
def load_tsv(
    path: Path,
    row0: int,
    x_num: np.memmap,
    ys: np.ndarray,
    keys: np.ndarray,
    n_features: int,
    n_workers: int,
) -> int:
    """Batch-based loader with constant memory usage. Returns rows written.
    
    Optimizations:
    - Batched reading (constant memory, independent of file size)
    - No redundant .astype() copies
    - Single pass (no count_rows pre-scan)
    - Direct memmap writes
    """
    # Column names: key, label, f_1, f_2, ..., f_K
    # Polars names headerless columns column_1, column_2, ... (1-based)
    key_col = "column_1"
    label_col = "column_2"
    feat_cols = [f"column_{i + 3}" for i in range(n_features)]
    
    # Schema: key=String, label=Float64, features=Float32
    schema = {key_col: pl.String, label_col: pl.Float64}
    for col in feat_cols:
        schema[col] = pl.Float32
    
    # Batched reader for constant memory
    reader = pl.read_csv_batched(
        str(path),
        separator="\t",
        has_header=False,
        try_parse_dates=False,
        null_values=list(NA_STRINGS),
        schema_overrides=schema,
        n_threads=n_workers,
        batch_size=BATCH_SIZE,
    )
    
    row = row0
    batch_idx = 0
    _t0 = time.perf_counter()
    
    while True:
        batches = reader.next_batches(BATCH_SIZE)
        if batches is None:
            break
        
        # Concatenate all batches into one DataFrame
        batch = pl.concat(batches)
        n = len(batch)
        sl = slice(row, row + n)
        
        # Labels: direct conversion (already Float64)
        labels = batch[label_col].to_numpy()
        if np.isnan(labels).any():
            bad = row - row0 + int(np.flatnonzero(np.isnan(labels))[0]) + 1
            sys.exit(f"error: {path} row {bad}: label is null/missing")
        ys[sl] = labels
        
        # Keys: polars hash (uint64 → int64 view)
        keys[sl] = batch[key_col].hash().to_numpy().view(np.int64)
        
        # Features: direct conversion (already Float32, no .astype() copy)
        x_num[sl, :] = batch.select(feat_cols).to_numpy()
        
        row += n
        batch_idx += 1
        
        if batch_idx % 10 == 0:
            print(f"  batch {batch_idx}: {row - row0:,} rows")
    
    _t1 = time.perf_counter()
    print(f"  Total: {row - row0:,} rows in {batch_idx} batches, "
          f"{_t1 - _t0:.2f}s ({(row - row0) / (_t1 - _t0):,.0f} rows/s)")
    
    return row - row0


# ── main ─────────────────────────────────────────────────────────────────────
def main() -> None:
    args = parse_args()
    splits = [
        (name, getattr(args, name))
        for name in ("train", "val", "test")
        if getattr(args, name) is not None
    ]
    for name, path in splits:
        if not path.is_file():
            sys.exit(f"error: --{name} file not found: {path}")

    # ── sniff feature count ──────────────────────────────────────────────────
    n_feats_seen = set()
    for name, path in splits:
        nf = sniff(path)
        n_feats_seen.add(nf)
    if len(n_feats_seen) != 1:
        sys.exit(f"error: inconsistent feature counts across files: {n_feats_seen}")
    n_features = n_feats_seen.pop()
    print(f"Features: {n_features}, workers: {args.n_workers}")

    # ── First pass: count rows (needed for memmap preallocation) ─────────────
    # This is the only "extra" pass, but it's fast (binary newline count)
    counts = {}
    for name, path in splits:
        n = 0
        with path.open("rb") as f:
            while block := f.read(1 << 24):
                n += block.count(b"\n")
        counts[name] = n
    
    n_total = sum(counts.values())
    print(f"Rows: {counts} (total {n_total})")

    # ── allocate outputs ─────────────────────────────────────────────────────
    args.out_dir.mkdir(parents=True, exist_ok=True)
    x_num = np.lib.format.open_memmap(
        args.out_dir / "x_num.npy", mode="w+",
        dtype=np.float32, shape=(n_total, n_features),
    )
    ys = np.empty(n_total, dtype=np.float64)
    keys = np.empty(n_total, dtype=np.int64)

    # ── convert (sequential, with full intra-file parallelism) ───────────────
    offsets = {}
    row = 0
    for name, path in tqdm(splits, desc="Files"):
        print(f"Loading {name} ({counts[name]:,} rows)...")
        n = load_tsv(path, row, x_num, ys, keys, n_features, args.n_workers)
        if n != counts[name]:
            sys.exit(f"error: {path}: parsed {n} rows, counted {counts[name]}")
        print(f"  {name}: rows [{row}, {row + n})")
        offsets[name] = (row, row + n)
        row += n
    
    x_num.flush()

    # ── y / key / info / splits ──────────────────────────────────────────────
    y_dtype = np.float32 if args.task_type == "regression" else np.int64
    y = ys.astype(y_dtype)
    np.save(args.out_dir / "y.npy", y)
    np.save(args.out_dir / "key.npy", keys)

    info = {"task": {"type": args.task_type, "score": TASK_SCORES[args.task_type]}}
    (args.out_dir / "info.json").write_text(json.dumps(info, indent=4) + "\n")

    split_dir = args.out_dir / "splits" / "default"
    split_dir.mkdir(parents=True, exist_ok=True)
    for name, (a, b) in offsets.items():
        np.save(split_dir / f"{name}.npy", np.arange(a, b, dtype=np.int32))

    print(f"\nSaved to {args.out_dir}:")
    print(f"  x_num.npy {x_num.shape} float32")
    print(f"  y.npy {y.shape} {y.dtype}")
    print(f"  key.npy {keys.shape} int64")
    print(f"  info.json")
    print(f"  splits/default/{{{', '.join(n for n, _ in splits)}}}.npy")
    
    if args.task_type != "regression":
        uniq, cnt = np.unique(y, return_counts=True)
        print(f"  label distribution: {dict(zip(uniq.tolist(), cnt.tolist()))}")
    
    print("\nDone.")


if __name__ == "__main__":
    main()
