function = "bin.mlp.main"
n_seeds = 15

[base_config]
batch_size = 256
n_epochs = -1
patience = 16
gradient_clipping_norm = 1.0

[base_config.data]
path = "data/churn"
cache = true
extract_bin_from_num = true
num_policy = "noisy-quantile"
bin_policy = "convert-to-cat"
cat_policy = "ordinal"

[base_config.model.backbone]
n_blocks = 1
d_block = 144
dropout = 0.10724753232870242

[base_config.optimizer]
type = "AdamW"
lr = 0.0005942137054568542
weight_decay = 0.0
